[build]
  command = "npm run build"
  publish = "../JongFlix/build"
  functions = "../JongFlix/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
